# Use the PHP 7.3 runtime (BETA) by replacing "php72" below with "php73"
runtime: php55

handlers:

- url: /
  script: index.php

- url: /index.*
  script: index.php

- url: /signup.*
  script: signup.php

- url: /newacc.*
  script: newacc.php
