runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /js
  static_dir: js

- url: /.*
  script: main.app

libraries:
- name: MySQLdb
  version: "latest"
- name: jinja2
  version: latest
- name: webapp2
  version: latest

# [START gae_python_mysql_env]
env_variables:
    CLOUDSQL_CONNECTION_NAME: map-cc-assignment:australia-southeast1:ccassign2locationdata
    CLOUDSQL_USER: davesarkies
    CLOUDSQL_PASSWORD: password
    CLOUDSQL_DB: locationdataformaps
# [END gae_python_mysql_env]
