runtime: python27
api_version: 1
threadsafe: yes

automatic_scaling:
  max_concurrent_requests: 12

handlers:

- url: /js
  static_dir: js

- url: /css
  static_dir: css
  
- url: /.*
  script: main.app
  secure: always

libraries:
- name: MySQLdb
  version: "latest"
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: ssl
  version: latest
